// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PantheonBackend.Models;

namespace PantheonBackend.Migrations
{
    [DbContext(typeof(PantheonBackendContext))]
    [Migration("20181216033455_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PantheonBackend.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("area");

                    b.Property<string>("name");

                    b.Property<float>("population");

                    b.HasKey("ID");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("PantheonBackend.Models.God", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountryID");

                    b.Property<string>("CountryName");

                    b.Property<string>("animal");

                    b.Property<string>("name");

                    b.Property<string>("power");

                    b.Property<string>("symbol");

                    b.HasKey("ID");

                    b.ToTable("God");
                });

            modelBuilder.Entity("PantheonBackend.Models.Hero", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountryID");

                    b.Property<string>("CountryName");

                    b.Property<int>("GodID");

                    b.Property<string>("GodName");

                    b.Property<int>("losses");

                    b.Property<string>("name");

                    b.Property<int>("victories");

                    b.Property<string>("weapon");

                    b.HasKey("ID");

                    b.ToTable("Hero");
                });
#pragma warning restore 612, 618
        }
    }
}
